version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: exchange_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=exchange_db
    ports:
      - '27017:27017'
